import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { inflateSync } from "node:zlib";
import { cardGroups, configToJson, parseInstructions } from "@washy-washy/core";
import { PDFDocument, PDFName, PDFRawStream } from "pdf-lib";
import { slug } from "../src/cli";
import { loadConfig } from "../src/config";

// The committed dummy config, not `data/washy-washy.json` — that one is
// gitignored, so on a fresh clone and in CI it is not there to read.
const CONFIG = "data/washy-washy.json.dist";

/** The six the README links, regenerated by `bun run examples`. */
const EXAMPLES = [
  "washy-washy-phone.pdf",
  "washy-washy-phone-washing.pdf",
  "washy-washy-phone-ironing.pdf",
  "washy-washy-print.pdf",
  "washy-washy-print-washing.pdf",
  "washy-washy-print-ironing.pdf",
];

/**
 * Every word a PDF actually draws.
 *
 * @react-pdf writes its text as hex-encoded `TJ` runs inside a Flate-compressed
 * content stream, so this inflates each page and pulls the strings back out.
 * Crude — it knows nothing about position, so a two-column row reads as one
 * line — but a sheet that has stopped drawing the iron is a sheet with no iron
 * words in it, and nothing softer than reading the ink proves that.
 */
async function words(pdf: Uint8Array): Promise<string> {
  const doc = await PDFDocument.load(pdf);
  return doc
    .getPages()
    .map((page) => {
      const stream = doc.context.lookup(page.node.get(PDFName.of("Contents")));
      if (!(stream instanceof PDFRawStream)) return "";
      const raw = Buffer.from(inflateSync(stream.contents)).toString("latin1");
      return [...raw.matchAll(/\[((?:\s*<[0-9a-fA-F]*>\s*-?[\d.]*)+)\]\s*TJ/g)]
        .map((run) =>
          [...(run[1] as string).matchAll(/<([0-9a-fA-F]*)>/g)]
            .map((chunk) => Buffer.from(chunk[1] as string, "hex").toString("latin1"))
            .join(""),
        )
        .join(" ");
    })
    .join(" ");
}

/**
 * What a document actually draws, page by page: its size and a hash of its
 * content stream.
 *
 * Not the file's bytes. Two runs over the same input write the same streams
 * but number them differently — @react-pdf writes them as they resolve — and
 * each run stamps its own creation date and file ID, so a byte comparison
 * fails on everything except what it was meant to catch. The page tree is
 * stable, and every stream hanging off it is identical.
 */
async function drawing(pdf: Buffer): Promise<string[]> {
  const doc = await PDFDocument.load(pdf);
  return doc.getPages().map((page) => {
    const contents = page.node.get(PDFName.of("Contents"));
    const stream = contents ? doc.context.lookup(contents) : undefined;
    const ink = stream instanceof PDFRawStream ? Bun.hash(stream.contents).toString(16) : "blank";
    return `${Math.round(page.getWidth())}x${Math.round(page.getHeight())} ${ink}`;
  });
}

/**
 * The outer test: run the tool exactly as a person would and check the two
 * PDFs that come out. Anything below this — parsing, mixing rules, layout —
 * only exists to make this pass.
 */
describe("bun run generate", () => {
  let out: string;
  let exitCode: number;
  let stdout: string;

  beforeAll(async () => {
    out = await mkdtemp(join(tmpdir(), "washing-"));
    const result = Bun.spawnSync({
      // Named explicitly. The default prefers your own config, which is
      // right for a person at a terminal and wrong for a test that has to
      // mean the same thing on every clone.
      cmd: ["bun", "run", "src/cli.ts", CONFIG, "--out", out],
      stdout: "pipe",
      stderr: "pipe",
    });
    exitCode = result.exitCode;
    stdout = result.stdout.toString() + result.stderr.toString();
  }, 120_000);

  afterAll(async () => {
    await rm(out, { recursive: true, force: true });
  });

  test("exits cleanly", () => {
    expect(stdout).not.toContain("error");
    expect(exitCode).toBe(0);
  });

  test("writes a phone PDF that is one continuous page", async () => {
    const pdf = await PDFDocument.load(await readFile(join(out, "washy-washy-phone.pdf")));
    expect(pdf.getPageCount()).toBe(1);

    const page = pdf.getPage(0);
    expect(page.getWidth()).toBeCloseTo(244, 0);
    // Tall enough to be a scroll sheet, but bisected down rather than padded.
    expect(page.getHeight()).toBeGreaterThan(page.getWidth() * 8);
  });

  test("writes a printable PDF, every page A4", async () => {
    const pdf = await PDFDocument.load(await readFile(join(out, "washy-washy-print.pdf")));
    const { config } = await loadConfig(CONFIG);
    const cards = cardGroups(config.chart).length;

    // The reference sheet, then the cards flowing over as many sheets as they
    // need. Two fit comfortably today, but a wordy row can push that to one.
    expect(pdf.getPageCount()).toBeGreaterThanOrEqual(1 + Math.ceil(cards / 2));
    expect(pdf.getPageCount()).toBeLessThanOrEqual(1 + cards);

    for (const page of pdf.getPages()) {
      expect(page.getWidth()).toBeCloseTo(595.28, 0);
      expect(page.getHeight()).toBeCloseTo(841.89, 0);
    }
  });

  /**
   * The split sheets. One run writes six files: the whole chart, the wash half
   * and the iron half, in each of the two shapes. The halves exist because the
   * two jobs happen in different rooms hours apart, and carrying the drying
   * advice to the ironing board is what makes a card too long to read.
   */
  describe("the washing-only and ironing-only sheets", () => {
    test("writes all six PDFs", async () => {
      for (const name of EXAMPLES) {
        expect(await Bun.file(join(out, name)).exists()).toBe(true);
      }
    });

    test("keeps the phone halves to one page of the same width", async () => {
      for (const name of ["-phone-washing.pdf", "-phone-ironing.pdf"]) {
        const pdf = await PDFDocument.load(await readFile(join(out, `washy-washy${name}`)));
        expect(pdf.getPageCount()).toBe(1);
        expect(pdf.getPage(0).getWidth()).toBeCloseTo(244, 0);
      }
    });

    test("keeps the print halves on A4 with nothing blank", async () => {
      for (const name of ["-print-washing.pdf", "-print-ironing.pdf"]) {
        const pdf = await PDFDocument.load(await readFile(join(out, `washy-washy${name}`)));
        for (const page of pdf.getPages()) {
          expect(page.getWidth()).toBeCloseTo(595.28, 0);
          expect(page.getHeight()).toBeCloseTo(841.89, 0);
          const stream = pdf.context.lookup(page.node.get(PDFName.of("Contents")));
          expect(stream instanceof PDFRawStream ? stream.contents.length : 0).toBeGreaterThan(1000);
        }
      }
    });

    test("the washing sheets say nothing about the iron", async () => {
      for (const name of ["-phone-washing.pdf", "-print-washing.pdf"]) {
        const text = await words(await readFile(join(out, `washy-washy${name}`)));
        expect(text).toContain("White Towels");
        expect(text).toContain("DETERGENT");
        expect(text).not.toContain("steam zone");
        expect(text).not.toContain("Do not iron");
      }
    });

    test("the ironing sheets say nothing about the machine", async () => {
      for (const name of ["-phone-ironing.pdf", "-print-ironing.pdf"]) {
        const text = await words(await readFile(join(out, `washy-washy${name}`)));
        expect(text).toContain("White Towels");
        expect(text).toContain("Do not iron");
        expect(text).not.toContain("clockwise from");
        expect(text).not.toContain("SOFTENER");
        expect(text).not.toContain("DRYING");
      }
    });

    /** One card per thermostat position, not one per pile. */
    test("gathers the ironing sheet by where the thermostat points", async () => {
      const text = await words(await readFile(join(out, "washy-washy-print-ironing.pdf")));
      // Six piles are never ironed. They share the card rather than getting six.
      expect(text).toContain("cotton, linen");
      expect(text.match(/Do not iron/g)?.length).toBeLessThan(3);
    });

    /**
     * The card has already said whether you iron the thing, so a pile whose
     * ironing notes are empty earns a blank rather than a line repeating the
     * refusal. A pile that says why keeps the why. True of every sheet that
     * draws an iron, not only the ironing ones.
     */
    test("never repeats the refusal under a card that has made it", async () => {
      for (const name of EXAMPLES) {
        const text = await words(await readFile(join(out, name)));
        // Capitalised: "don't press hard" mid-sentence is advice and stays.
        expect(text, name).not.toContain("Don't");
      }
    });

    test("keeps the piles and their reasons on the ironing sheets", async () => {
      for (const name of ["-phone-ironing.pdf", "-print-ironing.pdf"]) {
        const text = await words(await readFile(join(out, `washy-washy${name}`)));
        // The piles are still listed — it is the second column that emptied.
        expect(text).toContain("White Socks");
        expect(text).toContain("Gym Socks");
        expect(text).toContain("Ironing crushes the pile flat");
        expect(text).toContain("Elastane starts degrading");
      }
    });

    test("names all six in what it reports", () => {
      for (const name of EXAMPLES) expect(stdout).toContain(name);
    });
  });

  /**
   * The chart has always carried how long each programme runs. It used to
   * appear only in the corner of a card, which is no use when the question is
   * "have I got time before dinner" and you are looking at the pinned sheet.
   */
  test("puts the wash duration on the reference sheet and in the loads", async () => {
    const print = await words(await readFile(join(out, "washy-washy-print.pdf")));
    expect(print).toContain("Time");
    expect(print).toContain("~2:30");

    const phone = await words(await readFile(join(out, "washy-washy-phone.pdf")));
    expect(phone).toContain("~0:40");
  });

  test("reports how long each load takes", () => {
    expect(stdout).toMatch(/White \+ White Socks\s+~2:30/);
  });

  /**
   * The README links the PDFs under docs/ rather than describing them, so
   * a reader who opens one is reading the current chart or a lie. This run
   * used the chart and the appliances they were drawn from, so it has to draw
   * what they draw. `bun run examples` is the fix when it does not.
   */
  test("draws the examples committed under docs/", async () => {
    const stale: string[] = [];
    for (const name of EXAMPLES) {
      const fresh = await drawing(await readFile(join(out, name)));
      const committed = await drawing(await readFile(join("docs", name)));
      if (JSON.stringify(fresh) !== JSON.stringify(committed)) stale.push(`docs/${name}`);
    }

    expect(stale).toEqual([]);
  });

  test("reports which piles can share a drum", () => {
    expect(stdout).toContain("Piles that can share a drum");
    expect(stdout).toContain("Dark + Black Socks + Denim");
    expect(stdout).toContain("White + White Socks");
  });

  test("reports the piles that collapsed onto one card", () => {
    expect(stdout).toContain("sharing one card");
    expect(stdout).toContain("Merino Wool + Cashmere Blend");
  });

  test("says which appliances it drew for", () => {
    expect(stdout).toContain("Generic front loader");
  });

  /**
   * One PDF per card, not per pile — a pile sharing a card with another
   * (Merino Wool + Cashmere Blend) shares its file too, matching what
   * `renderPrint` already draws as a single card for both.
   */
  describe("per-pile card PDFs", () => {
    test("writes one card PDF per card group, named after its piles", async () => {
      const { config } = await loadConfig(CONFIG);
      const cards = cardGroups(config.chart);
      expect(stdout).toContain(`${cards.length} card PDF`);

      expect(await Bun.file(join(out, "washy-washy-card-white.pdf")).exists()).toBe(true);
      expect(
        await Bun.file(join(out, "washy-washy-card-merino-wool+cashmere-blend.pdf")).exists(),
      ).toBe(true);
    });

    test("renders a pile's reference citation on its own card", async () => {
      const pdf = await readFile(join(out, "washy-washy-card-merino-wool+cashmere-blend.pdf"));
      const text = await words(pdf);
      expect(text).toContain("Icebreaker on merino");
    });

    test("keeps every card to one page, nothing near-blank", async () => {
      const { config } = await loadConfig(CONFIG);
      for (const group of cardGroups(config.chart)) {
        const name = group.map((item) => slug(item.clothingType)).join("+");
        const pdf = await PDFDocument.load(
          await readFile(join(out, `washy-washy-card-${name}.pdf`)),
        );

        expect(pdf.getPageCount()).toBe(1);
        const stream = pdf.context.lookup(pdf.getPage(0).node.get(PDFName.of("Contents")));
        expect(stream instanceof PDFRawStream ? stream.contents.length : 0).toBeGreaterThan(1000);
      }
    });
  });

  /**
   * A machine with longer programme names once widened the summary table by
   * enough to push the reference sheet a point past A4, and @react-pdf answers
   * a page it cannot fit with an empty sheet rather than an error. Nothing
   * failed: the page count stayed inside its allowed range and the blank sheet
   * only turned up when someone printed it.
   */
  test("prints no blank pages", async () => {
    const pdf = await PDFDocument.load(await readFile(join(out, "washy-washy-print.pdf")));

    const ink = pdf.getPages().map((page) => {
      const contents = page.node.get(PDFName.of("Contents"));
      const stream = contents ? pdf.context.lookup(contents) : undefined;
      return stream instanceof PDFRawStream ? stream.contents.length : 0;
    });

    expect(ink.filter((bytes) => bytes < 1000)).toEqual([]);
  });
});

/**
 * The whole point of the machine half of the config: the same chart, a
 * different fascia. Nothing in the code knows what a programme is called.
 */
describe("bun run generate, a different machine", () => {
  test("draws whatever machine the config names", async () => {
    const dir = await mkdtemp(join(tmpdir(), "machine-"));
    const config = join(dir, "config.json");

    const machine = {
      washer: {
        name: "Zanussi ZWF",
        capacity: "7 kg",
        programs: ["Arrêt", "Coton", "Synthétiques", "Laine"],
        temperatures: ["froid", "30", "40"],
        spins: ["0", "1000"],
        options: ["Prélavage"],
      },
      iron: {
        name: "Calor Pro",
        settings: [
          { key: "1", dots: "•", label: "•", detail: "synthétiques", steam: false },
          { key: "2", dots: "••", label: "••", detail: "laine", steam: true },
        ],
      },
    };
    const csv =
      "clothing_type,detergent,fabric_softener,temperature,spin,duration,program,options," +
      "ironing,ironing_notes,iron_setting,drying,colour_group,mix_tags,notes,reference_name,reference_link\n" +
      "Linge blanc,Lessive,no,40,1000,~2:00,Coton,Prélavage,yes,Fer chaud,2,Étendre,white,,,,\n" +
      "Pulls,Lessive laine,no,30,0,~0:40,Laine,,no,,,À plat,any,,,,\n";
    const chart = parseInstructions(csv, machine);
    await writeFile(config, configToJson({ machine, chart }));

    const result = Bun.spawnSync({
      cmd: ["bun", "run", "src/cli.ts", config, "--out", dir],
      stdout: "pipe",
      stderr: "pipe",
    });
    const output = result.stdout.toString() + result.stderr.toString();

    expect(output).toContain("Zanussi ZWF");
    expect(result.exitCode).toBe(0);
    expect(await Bun.file(join(dir, "config-print.pdf")).exists()).toBe(true);

    await rm(dir, { recursive: true, force: true });
  }, 120_000);

  test("refuses a chart written for a different machine, and says which value", async () => {
    // The committed config's chart, kept, but embedded with a machine that
    // does not know any of its programme or option names.
    const dir = await mkdtemp(join(tmpdir(), "other-"));
    const config = join(dir, "config.json");
    const otherMachine = {
      washer: {
        name: "Some Other Washer",
        capacity: "8 kg",
        programs: ["Uit", "Katoen", "Wol"],
        temperatures: ["koud", "30", "60"],
        spins: ["0", "1200"],
        options: ["Extra spoelen"],
      },
      iron: {
        name: "Some Other Iron",
        settings: [
          { key: "1", dots: "•", label: "•", detail: "", steam: false },
          { key: "2", dots: "••", label: "••", detail: "", steam: true },
        ],
      },
    };
    const { chart } = JSON.parse(await readFile(CONFIG, "utf8"));
    await writeFile(config, JSON.stringify({ machine: otherMachine, chart }));

    const result = Bun.spawnSync({
      cmd: ["bun", "run", "src/cli.ts", config, "--out", dir],
      stdout: "pipe",
      stderr: "pipe",
    });

    expect(result.exitCode).toBe(1);
    expect(result.stderr.toString()).toMatch(/row 2, column "(program|options)"/);

    await rm(dir, { recursive: true, force: true });
  }, 60_000);
});
